stages:
        #  - test
#  - build
  - mirror
  - deploy

    #lint:
    #stage: test

#compile:
#  stage: build
#  script:
#    - docker build -t sockleblu/blog_frontend .

sync_to_github:
  stage: mirror
  tags:
    - pena
    - linux
  script:
    - if [[ $(git remote -v | grep github) ]]; then
    -     echo 'github already added as remote'
    - else
    -     git remote add github git@github.com:sockleblu/digital_garden_frontend.git
    - fi
    - git push github HEAD:refs/heads/master

run:
  stage: deploy
  tags:
    - blog
  script:
    - cd /vagrant/export && sudo chef-client -z
    - cd /var/www/blog/master && yarn install
    - cd /var/www/blog/master && yarn run build
    - systemctl restart blog_frontend

